### ISSUE TITLE
Add GMP support on Windows

### ISSUE THREAD

**Issue by AntoinePrv** [conda-forge/scipoptsuite-feedstock#15]
Add supp

- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.
- [ ] Try using the `m2w64-gmp` package to add GMP (and then ZIMPL) support on Windows.

**Comment by isuruf** [comment]
You can use `mpir` which is a drop in replacement on windows

**Comment by AntoinePrv** [comment]
Closed in #54
