### ISSUE TITLE
Remove the use of GPL lbraries (readline, gsl)

### ISSUE THREAD

**Issue by isuruf** [conda-forge/scipoptsuite-feedstock#2]
I didn't see this at the code review, but ZIB and GPL don't go together. So, please remove GPL dependencies. This issue is mentioned in https://www.scipopt.org/index.php#license.

cc @conda-forge/core

**Comment by AntoinePrv** [comment]
Thanks for pointing this out @isuruf. Does it change anything if the libraries are linked dynamically?

**Comment by AntoinePrv** [comment]
@isuruf actually, `gsl` is used only in for the `gcg` subpackage, which is licensed under LGPL
https://gcg.or.rwth-aachen.de/#license

But it is not possible to have licenses for `outputs` in `conda-build`. We can add again `gsl` and package the LGPL license for `gcg`.

**Comment by isuruf** [comment]
> gsl is used only in for the gcg subpackage, which is licensed under LGPL

But gcg has scip as a dependency right?

**Comment by AntoinePrv** [comment]
Yes. Would that prevent it from from using LGPL dependencies?

Python itself [seems to be using `readline`](https://github.com/conda-forge/python-feedstock/blob/8fae6d37ed0e54039822db89a78ab38a76db0110/recipe/meta.yaml#L214), would that mean it's forbidden to distribute proprietary native Python packages?
I argree we should not link `SCIP` with `readline`, but in the case of `gcg` with `gsl` it does not seem so clear to me.

**Comment by AntoinePrv** [comment]
Or perhaps, looking at it the other way, we could ask the ZIB team the licensing more details about the implications to dynamically link against `scip`.

**Comment by isuruf** [comment]
> Yes. Would that prevent it from from using LGPL dependencies?

IANAL, so can't say it does or not. To be on the safe side we could remove GSL.

cc @conda-forge/core
